In [1]:
import numpy as np
import pandas as pd

In [2]:
si_data = pd.read_csv("/workspaces/service-data/outputs/snapshots/2025-03-01/utils/si_all.csv", sep=";")

In [3]:
si23 = si_data[si_data["fiscal_yr"] == "2023-2024"].copy()
si22 = si_data[si_data["fiscal_yr"] == "2022-2023"].copy()
siEnd22 = si_data.query("fiscal_yr in ['2018-2019', '2019-2020', '2020-2021', '2021-2022', '2022-2023']").copy()

In [4]:
si23_ext = si23[si23["service_scope_ext_or_ent"]]
si22_ext = si22[si22["service_scope_ext_or_ent"]]

In [5]:
print(f"In 2023-24, there are {si23.shape[0]} services reported, of which {si23_ext.shape[0]} are extern/enterprise, and {si22_ext.shape[0]} services in 2022-23.")

In 2023-24, there are 1715 services reported, of which 1681 are extern/enterprise, and 1690 services in 2022-23.

In [12]:
#si23_ext.count()

In [10]:
si23_ext.columns

Index(['fiscal_yr', 'service_id', 'service_name_en', 'service_name_fr',
       'service_description_en', 'service_description_fr', 'service_type',
       'service_recipient_type', 'service_scope', 'client_target_groups',
       'program_name_en', 'program_name_fr', 'client_feedback_channel',
       'service_fee', 'last_GBA', 'ident_platform', 'ident_platform_comments',
       'os_account_registration', 'os_authentication', 'os_application',
       'os_decision', 'os_issuance', 'os_issue_resolution_feedback',
       'os_comments_client_interaction_en',
       'os_comments_client_interaction_fr',
       'how_has_the_service_been_assessed_for_accessibility',
       'last_service_review', 'last_service_improvement', 'sin_usage',
       'cra_bn_identifier_usage', 'num_phone_enquiries',
       'num_applications_by_phone', 'num_website_visits',
       'num_applications_online', 'num_applications_in_person',
       'num_applications_by_mail', 'num_applications_by_email',
       'num_applications_by_fax', 'num_applications_by_other',
       'special_remarks_en', 'special_remarks_fr', 'service_uri_en',
       'service_uri_fr', 'num_applications_total', 'org_name_variant',
       'org_id', 'department_en', 'department_fr', 'program_id',
       'automated_decision_system_description_fr', 'automated_decision_system',
       'automated_decision_system_description_en', 'service_scope_ext_or_ent',
       'fy_org_id_service_id'],
      dtype='object')

In [13]:
prog_cols = ["fiscal_yr", "service_id", "service_name_en", "program_id", "program_name_en", "org_name_variant", "org_id", "department_en"]

In [18]:
org_names = list(set(si23_ext["org_name_variant"].values))
Nlines = int(len(org_names) / 10)
for k in range(Nlines):
    if k*10 < len(org_names):
        print(", ".join(org_names[k*10:k*10+10]))
print(", ".join(org_names[(Nlines)*10:]))

dfatd-maecd, psc-cfp, cbsa-asfc, tbs-sct, aandc-aadnc, hc-sc, nrc-cnrc, fja-cmf, csec-cstc, sshrc-crsh
fednor, opc-cpvp, pbc-clcc, ps-sp, nserc-crsng, pch, prairiescan, oag-bvg, fpcc-cpac, nfb-onf
aafc-aac, wage, esdc-edsc, pmprb-cepmb, mpcc-cppm, fcac-acfc, csa-asc, cra-arc, statcan, ppsc-sppc
polar-polaire, atssc-scdata, phac-aspc, csps-efpc, osfi-bsif, vac-acc, infc, fintrac-canafe, isc-sac, cics-scic
pwgsc-tpsgc, nrcan-rncan, lac-bac, tc, nsira-ossnr, ccohs-cchst, ced-dec, vrab-tacra, ic, cer-rec
cgc-ccg, cic, jus, pco-bcp, dnd-mdn, ssc-spc, ec, pacifican, cannor, pc
cas-satj, irb-cisr, cpc-cpp, nbc-ccbn, csc-scc, cta-otc, cihr-irsc, dfo-mpo, fin, acoa-apeca
chrc-ccdp, cb-cda, feddevontario, cfia-acia, oci-bec, crtc, rcmp-grc, iaac-aeic

In [25]:
org_ids = list(set(si23_ext["org_id"].values))
Nlines = int(len(org_ids) / 10)
for k in range(Nlines):
    if k*10 < len(org_ids):
        print(" ".join([f"{i:.0f}" for i in org_ids[k*10:k*10+10]]))
print(" ".join([f"{i:.0f}" for i in org_ids[(Nlines)*10:]]))

1 12 26 539 552 46 47 560 561 55
63 65 69 71 74 76 86 93 95 99
110 114 117 118 122 123 124 125 126 127
128 129 130 132 133 134 135 136 137 138
139 140 141 150 151 152 174 199 210 218
221 222 223 227 228 230 237 238 240 246
247 248 253 256 263 266 278 280 282 295
297 302 305 306 313 326 333 348

In [28]:
si_prog = si23_ext.filter(prog_cols).copy()

In [29]:
si_prog[:4]

,fiscal_yr,service_id,service_name_en,program_id,program_name_en,org_name_variant,org_id,department_en
7249,2023-2024,3596,ATSSC General Inquiries,ISSA2,'Communications Services',atssc-scdata,539.0,Administrative Tribunals Support Service of Ca...
7250,2023-2024,3597,ATSSC Registry Services,BEE01,'Registry Services',atssc-scdata,539.0,Administrative Tribunals Support Service of Ca...
7251,2023-2024,3598,Access to Information and Privacy,ISS02,'Communications Services',atssc-scdata,539.0,Administrative Tribunals Support Service of Ca...
7252,2023-2024,2224,AAFC Contact Centre,BWN02,'Sector Engagement and Development',aafc-aac,1.0,Agriculture and Agri-Food Canada

In [32]:
si_prog["org_id"] = si_prog["org_id"].astype(int)
si_prog["prog_dept"] = si_prog["program_id"] + "-" + si_prog["org_id"].astype(str)

In [33]:
si_prog[:4]

,fiscal_yr,service_id,service_name_en,program_id,program_name_en,org_name_variant,org_id,department_en,prog_dept
7249,2023-2024,3596,ATSSC General Inquiries,ISSA2,'Communications Services',atssc-scdata,539,Administrative Tribunals Support Service of Ca...,ISSA2-539
7250,2023-2024,3597,ATSSC Registry Services,BEE01,'Registry Services',atssc-scdata,539,Administrative Tribunals Support Service of Ca...,BEE01-539
7251,2023-2024,3598,Access to Information and Privacy,ISS02,'Communications Services',atssc-scdata,539,Administrative Tribunals Support Service of Ca...,ISS02-539
7252,2023-2024,2224,AAFC Contact Centre,BWN02,'Sector Engagement and Development',aafc-aac,1,Agriculture and Agri-Food Canada,BWN02-1