In [57]:
import pandas as pd
import numpy as np

In [58]:
# Service inventory data
si_data = pd.read_csv("/home/jovyan/work/service-data/outputs/snapshots/2025-03-01/utils/si_all.csv", sep=';')

In [59]:
si23 = si_data[si_data["fiscal_yr"] == "2023-2024"].copy()
si22 = si_data[si_data["fiscal_yr"] == "2022-2023"].copy()
siEnd22 = si_data.query("fiscal_yr in ['2018-2019', '2019-2020', '2020-2021', '2021-2022', '2022-2023']").copy()

In [60]:
si23_ext = si23[si23["service_scope_ext_or_ent"]]
si22_ext = si22[si22["service_scope_ext_or_ent"]]

In [61]:
print(f"In 2023-24, there are {si23.shape[0]} services reported, of which {si23_ext.shape[0]} are extern/enterprise, and {si22_ext.shape[0]} services in 2022-23.")

In 2023-24, there are 1715 services reported, of which 1681 are extern/enterprise, and 1690 services in 2022-23.

In [62]:
# Service standard data
ss_data = pd.read_csv("/home/jovyan/work/service-data/outputs/snapshots/2025-03-01/utils/ss_all.csv", sep=';')

In [63]:
ss_data.count()

fiscal_yr                     12767
service_id                    12766
service_name_en               12766
service_name_fr               12766
service_standard_id           12765
service_standard_en           12748
service_standard_fr           12695
type                          12766
gcss_tool_fiscal_yr            5724
channel                       12766
channel_comments_en            4346
channel_comments_fr            4386
target_type                   10424
target                        12483
volume_meeting_target         11695
total_volume                  11818
performance                    9419
comments_en                    4788
comments_fr                    4793
target_met                    10188
standards_targets_uri_en       8974
standards_targets_uri_fr       9001
performance_results_uri_en     2878
performance_results_uri_fr     3021
org_name_variant              12766
org_id                        12766
department_en                 12766
department_fr                 12766
fy_org_id_service_id          12766
dtype: int64

In [64]:
ss23 = ss_data.query("fiscal_yr == '2023-2024'").copy()
ss22 = ss_data.query("fiscal_yr == '2022-2023'").copy()

In [65]:
ss23.shape

(2336, 29)

In [66]:
ss23_wtarget = ss23[~ss23["target"].isna()]
ss23_wtarget.shape

(2217, 29)

In [67]:
ss23_notarget = ss23[ss23["target"].isna()]
ss23_notarget.shape

(119, 29)

In [68]:
target_cols = ["fiscal_yr", "service_id", "service_name_en", "service_standard_id", "service_standard_en", "type", "target_type", "target", "volume_meeting_target", "total_volume", "performance", "target_met", "department_en"]
ss23_notarget[target_cols].head(10)

,fiscal_yr,service_id,service_name_en,service_standard_id,service_standard_en,type,target_type,target,volume_meeting_target,total_volume,performance,target_met,department_en
10846,2023-2024,1887,Client Services,2190,"Telephone, TTY and chats: Mon to Fri, 8:30 a.m...",TML,NaN,NaN,NaN,NaN,NaN,NaN,Canadian Radio-television and Telecommunicatio...
10872,2023-2024,3638,Stratospheric Balloon Flight Opportunities (ST...,8620,An answer is provided within 14 business follo...,TML,NaN,NaN,NaN,NaN,NaN,NaN,Canadian Space Agency
10884,2023-2024,SRV03429,Core geospatial observation sites in remote lo...,8729,No service standard established.,OTH,NaN,NaN,NaN,NaN,NaN,NaN,Canadian Space Agency
10912,2023-2024,1120,Issuance of licences for the use of copyright ...,1073,Licences are issued within 45 days once the fi...,TML,NaN,NaN,NaN,NaN,NaN,NaN,Copyright Board Canada
10913,2023-2024,1119,Copyright Tariff Setting,3961,Percentage of tariff decisions published withi...,TML,NaN,NaN,NaN,NaN,NaN,NaN,Copyright Board Canada
10930,2023-2024,2126,Support in accordance with the Addition of Lan...,3876,Scheduling of First Nations to the FNFMA,OTH,NaN,NaN,NaN,NaN,NaN,NaN,Crown-Indigenous Relations and Northern Affair...
10931,2023-2024,2477,Support in accordance with the First Nations F...,3878,Scheduling of First Nations,OTH,NaN,NaN,NaN,NaN,NaN,NaN,Crown-Indigenous Relations and Northern Affair...
10933,2023-2024,2122,Northern Contaminants Program,3881,To make payments under all funding agreements ...,ACY,NaN,NaN,NaN,NaN,NaN,NaN,Crown-Indigenous Relations and Northern Affair...
10941,2023-2024,2128,Ministerial Correspondence,3894,"Urgent correspondence: 6 business days, SVIP c...",TML,NaN,NaN,NaN,NaN,NaN,NaN,Crown-Indigenous Relations and Northern Affair...
10944,2023-2024,2564,Contribution and Loan Funding to support Indig...,3925,To send an acknowledgement of receipt of a pro...,TML,NaN,NaN,NaN,NaN,NaN,NaN,Crown-Indigenous Relations and Northern Affair...

In [69]:
# Service standards matched to extern/enterprise services
id_si23_ext = set(si23_ext["service_id"].values)
ss23_notarget_ext = ss23_notarget[ss23_notarget["service_id"].isin(id_si23_ext)]
ss23_notarget_ext.shape

(119, 29)

In [70]:
ss23_notarget_vol = ss23_notarget[~ss23_notarget["total_volume"].isna()]
ss23_notarget_vol.shape

(43, 29)

In [71]:
ss23_notarget_vol[target_cols][:10]

,fiscal_yr,service_id,service_name_en,service_standard_id,service_standard_en,type,target_type,target,volume_meeting_target,total_volume,performance,target_met,department_en
11169,2023-2024,SRV02793,Meteorological Support for Environmental Emerg...,STAN00005148,The Environmental Emergency Response Section p...,TML,NaN,NaN,5.0,5.0,1.0000,NaN,Environment and Climate Change Canada
11170,2023-2024,SRV02793,Meteorological Support for Environmental Emerg...,STAN00005149,The Environmental Emergency Response Section p...,TML,NaN,NaN,12.0,12.0,1.0000,NaN,Environment and Climate Change Canada
11171,2023-2024,SRV02793,Meteorological Support for Environmental Emerg...,STAN00005150,The Environmental Emergency Response Section p...,TML,NaN,NaN,3.0,3.0,1.0000,NaN,Environment and Climate Change Canada
11172,2023-2024,SRV02793,Meteorological Support for Environmental Emerg...,STAN00005151,The Environmental Emergency Response Section i...,TML,NaN,NaN,2.0,3.0,0.6667,NaN,Environment and Climate Change Canada
11202,2023-2024,1855,Travel Information Program,3959,Urgent Travel Advice and Advisories updates,TML,NaN,NaN,4038.0,4038.0,1.0000,NaN,Global Affairs Canada
11203,2023-2024,1855,Travel Information Program,3960,Non-urgent Travel Advice and Advisories updates,TML,NaN,NaN,4038.0,4038.0,1.0000,NaN,Global Affairs Canada
11204,2023-2024,1855,Travel Information Program,STAN00005687,Mandatory Cyclical Revisions,ACY,NaN,NaN,49.0,55.0,0.8909,NaN,Global Affairs Canada
11220,2023-2024,1699,Authentication of documents,STAN00005274,Canada now is a party to the Apostille Convent...,ACY,NaN,NaN,NaN,20000.0,NaN,NaN,Global Affairs Canada
11221,2023-2024,SRV02838,Public Enquiries Services,STAN00005203,Answer enquiries by email and voice messages w...,TML,NaN,NaN,19224.0,19224.0,1.0000,NaN,Global Affairs Canada
11235,2023-2024,SRV03126,Mission Readiness & Security Operations,8386,"Mission Secuity Feedback (CCTV, Floorplan, etc.)",TML,NaN,NaN,12.0,12.0,1.0000,NaN,Global Affairs Canada

In [72]:
ss23_notarget_vol_vmt = ss23_notarget_vol[~ss23_notarget_vol["volume_meeting_target"].isna()]
ss23_notarget_vol_vmt.shape

(38, 29)

In [73]:
ss23_notarget_vol_bydept = ss23_notarget_vol.groupby("department_en").size().reset_index(name="number_ss")
ss23_notarget_vol_bydept = ss23_notarget_vol_bydept.sort_values(by=["number_ss"], ascending=False)
ss23_notarget_vol_bydept[:10]

                                       department_en  number_ss
3                           Natural Resources Canada         16
1                              Global Affairs Canada         10
7                                   Transport Canada          8
0              Environment and Climate Change Canada          4
2                                      Health Canada          1
4  Offices of the Information and Privacy Commiss...          1
5                                       Parks Canada          1
6                             Shared Services Canada          1
8               Treasury Board of Canada Secretariat          1

In [74]:
# Standards with no target by department
ss23_notarget_bydept = ss23_notarget.groupby("department_en").size().reset_index(name="number_ss")
ss23_notarget_bydept = ss23_notarget_bydept.sort_values(by=["number_ss"], ascending=False)
ss23_notarget_bydept[:10]

                                        department_en  number_ss
8                            Natural Resources Canada         24
5                               Global Affairs Canada         20
15                                   Transport Canada         14
14               The National Battlefields Commission         12
4               Environment and Climate Change Canada         10
3   Crown-Indigenous Relations and Northern Affair...          9
7                                 National Film Board          9
10                                       Parks Canada          4
16               Treasury Board of Canada Secretariat          3
12                      Royal Canadian Mounted Police          3

In [75]:
ss23_notarget_bydept[20:30]

Empty DataFrame
Columns: [department_en, number_ss]
Index: []

In [76]:
ss23_notarget[~ss23_notarget["target_met"].isna()].shape

(0, 29)

In [77]:
ss23_notarget.to_csv("service_standards_no_target.csv", sep=";")

In [78]:
ss23_notarget_vol.to_csv("service_standards_no_target_with_volume.csv", sep=";")

In [79]:
# Standards with both volume empty
ss_both_volume_empty = ss23_notarget[ss23_notarget["volume_meeting_target"].isna() & ss23_notarget["total_volume"].isna()]
ss_both_volume_empty.shape

(76, 29)

In [80]:
#ss_both_volume_empty[target_cols][:10]

In [81]:
# Standards with only total volume empty but volume_meeting_target is filled
ss_totalVolume_empty = ss23_notarget[~ss23_notarget["volume_meeting_target"].isna() & ss23_notarget["total_volume"].isna()]
ss_totalVolume_empty.shape

(0, 29)

In [82]:
# Standards with total volume empty fillled but volume_meeting_target empty
ss_volMeetTarget_empty = ss23_notarget[ss23_notarget["volume_meeting_target"].isna() & ~ss23_notarget["total_volume"].isna()]
ss_volMeetTarget_empty.shape

(5, 29)

In [83]:
# Standard with total volume == zero
ss_totalVolume_zero = ss23_notarget[ss23_notarget["total_volume"] == 0]
ss_totalVolume_zero.shape

(13, 29)

In [85]:
# standards with total volume > zero and volume meeting target is zero or greater
ss_have_both_volume = ss23_notarget[~ss23_notarget["volume_meeting_target"].isna() & ~ss23_notarget["total_volume"].isna() & ss23_notarget["total_volume"] > 0]
ss_have_both_volume.shape

(25, 29)